upstream ml_service {
    server ml-blue:8000;
}

server {
    listen 80;

    location / {
        proxy_pass http://ml_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://ml_service/health;
    }

    location /predict {
        proxy_pass http://ml_service/predict;
    }
}
